### DISCUSSION TITLE
Map project descriptor top-level (`_`) keys to OCI annotations

### DISCUSSION THREAD

**Discussion by jromero** [buildpacks/community#101] [Ideas]
Based on a discussion with @samj1912 and previously inspired by https://github.com/buildpacks/pack/issues/1049, I'd like to propose that we map the [ top-level (`_`) project descriptor keys](https://github.com/buildpacks/spec/blob/3d25ba05805a41e95083874f5fedf2da0bcd2538/extensions/project-descriptor.md#_) to [OCI annotations](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys).

## Mapping

```toml
[_]
schema-version = "<schema-version>"
id = "<string>"
name = "<string>" # → org.opencontainers.image.title
version = "<string>" # →  org.opencontainers.image.version
authors = ["<string>"] # →  org.opencontainers.image.authors
documentation-url = "<uri>" # →  org.opencontainers.image.documentation
source-url = "<uri>" # →  org.opencontainers.image. source

[[_.licenses]] # →  org.opencontainers.image.licenses
type = "<string>"
uri = "<uri>"
```

 - Arrays could be mapped to comma separated values.

## Questions

 - What component would be responsible for this? platform, lifecycle, "prepare" phase?
 - Should we map `name` → `...description` so that we can map `id` → `...title`?
