### DISCUSSION TITLE
Convention: app source metadata

### DISCUSSION THREAD

**Discussion by jromero** [buildpacks/community#120] [Ideas]
If I recall correctly, when [RFC#13](https://github.com/buildpacks/rfcs/blob/main/text/0013-app-layer-metadata-source.md) (app source metadata) was introduced, the concrete specification for how different type of sources would be represented was left out of the [specification](https://github.com/buildpacks/spec/pull/81/files). I believe this was in order to allow for conventions to fill the need of countless possible types.

I'd like to propose the following conventions to be used on pack and for them to be codified as "conventions" in https://buildpacks.io/docs/.

### Type `git`

Based on already completed work on [kpack](https://github.com/pivotal/kpack/pull/287):

```toml
[source]
type = "git"

  [source.version]
  commit = "63a73f1b0f2a4f6978c19184b0ea33ad3f092913"
  describe = "v0.18.1-2-g3f092913"

  [source.metadata]
  refs = ["master", "v3.0"]
  repository = "https://github.com/myorg/myrepo.git"
```

### Type `image`

When source is an image (kpack feature):

```toml
[source]
type = "image"

  [source.version]
  digest = "146c4bce42545e6a4575283b32a7f01924ef86ce848273079693a42b52b27321"

  [source.metadata]
   path = "/source"
   repository =  "index.docker.io/example/image"
   refs = ["example/image:mytag"]
```

### Type `project`

When declared in `project.toml` as:

```toml
[project]
version = "1.0.2"
source-url = "https://github.com/buildpacks/pack"
```

The generated metadata would be:

```toml
[source]
type = "project"

  [source.version]
  declared = "1.0.2"

  [source.metadata]
  url = "https://github.com/buildpacks/pack"
```

## Open Questions

  - What's expected from the platform when the source has both `.git` information as well as `project.toml`?
      - Proposal: ~~In the short term, `.git` takes precedence over `project.toml` due to its more precise nature.~~
      - Proposal: see [Alternative](https://github.com/buildpacks/community/discussions/120#discussioncomment-1082492)

**Comment by jromero** [comment]
## Alternative

As an alternative to having `project.toml` compete with other types. I wonder if `project.toml` could simply augment the other types.


#### `project.toml`

For example, given `project.toml`:

```toml
[project]
version = "1.0.2"
source-url = "https://github.com/buildpacks/pack"
```

#### ... with Git information

and some `.git/` or [`git.properties`](https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/master/docs/using-the-plugin-in-more-depth.md) information, the following would be the aggregate:

```toml
[source]
type = "git"

  [source.version]
  # from project.toml
  version = "1.0.2"
  # from git
  commit = "63a73f1b0f2a4f6978c19184b0ea33ad3f092913"
  # from git
  describe = "v0.18.1-2-g3f092913"

  [source.metadata]
  # from project.toml
  url = "https://github.com/buildpacks/pack"
  # from git
  refs = ["master", "v3.0"]
  # from git
  repository = "https://github.com/myorg/myrepo.git"
```

#### ... with Image information

and some image information, the following would be the aggregate:

```toml
[source]
type = "image"

  [source.version]
  # from project.toml
  version = "1.0.2"
  # from image
  digest = "146c4bce42545e6a4575283b32a7f01924ef86ce848273079693a42b52b27321"

  [source.metadata]
  # from project.toml
  url = "https://github.com/buildpacks/pack"
  # from image
   path = "/source"
  # from image
  repository =  "index.docker.io/example/image"
  # from image
  refs = ["example/image:mytag"]
```
