### DISCUSSION TITLE
Build image directly in Kubernetes (e.g. using Kubernetes Job)

### DISCUSSION THREAD

**Discussion by collimarco** [buildpacks/community#136] [Q&A]
I have read the docs multiple times, but I can't find an answer.

Is there any way to build an image, using `pack` or similar, directly inside a Kubernetes pod / job?

Example:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: build-app-image-with-buildpacks
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: build-app-image-with-buildpacks
          image: buildpacksio/pack:latest
          command: ['build']
          args: ['<my-image> --builder <builder-image>']
          env: …
```

Is there any way to specify in the args that we want to download the app source code from a git repo and upload it to a docker registry?

Here's an ideal workflow:

1. Run a `Job` in Kubernetes
2. The `Job` launches a `pack` container passing some argments
3. The `pack` container automatically downloads source code from a git repo and uploads the built image to a registry

Is it possible to achieve that?
