### DISCUSSION TITLE
failed to copy linked module directory to layer path: failed to copy: destination exists

### DISCUSSION THREAD

**Discussion by arezvani** [buildpacks/community#269] [Q&A]
I have this image:

```yaml
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  labels:
    app: myapp002357
    type: build
  name: myapp002357
  namespace: test
spec:
  build:
    env:
    - name: BP_NODE_VERSION
      value: "18.20.8"
    resources:
      limits:
        cpu: "2"
        ephemeral-storage: 10G
        memory: 4G
      requests:
        cpu: 100m
        ephemeral-storage: 100M
        memory: 100M
  builder:
    kind: ClusterBuilder
    name: nodejs-jammy-full
  failedBuildHistoryLimit: 1
  imageTaggingStrategy: BuildNumber
  serviceAccountName: kpack-image-sa-myapp002356
  source:
    git:
      revision: main
      url: https://gitlab.example.com/test/app-doc.git
  successBuildHistoryLimit: 1
  tag: registry.example.com/test/myapp00239:v2
```

I have a problem with this and in build stage, I get this error:

failed to copy linked module directory to layer path: failed to copy: destination exists: remove /layers/paketo-buildpacks_npm-install: directory not empty

Also I don't have package-lock.json file and node modules in my repo.

Can anyone help me? What should I do?
